#!/usr/bin/expect -f
set timeout -1
set pass ")r5SSq({Qrjb,Z\[%"
set host "45.76.153.98"
set user "root"

spawn ssh -o StrictHostKeyChecking=no $user@$host
expect "password:"
send "$pass\r"
expect "# "

send "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y\r"
expect "# "

send "source \$HOME/.cargo/env\r"
expect "# "

send "tar -xzf sync-server.tar.gz\r"
expect "# "

send "cd sync-server && cargo build --release\r"
expect "# "

send "exit\r"
expect eof
