#!/usr/bin/expect -f
set timeout -1
set pass ")r5SSq({Qrjb,Z\[%"
set host "45.76.153.98"
set user "root"

spawn ssh -o StrictHostKeyChecking=no $user@$host
expect "password:"
send "$pass\r"
expect "# "

send "cd sync-server\r"
expect "# "

send "cp config.example.toml config.toml\r"
expect "# "

send "nohup target/release/synabit-sync-server > server.log 2>&1 &\r"
expect "# "

send "exit\r"
expect eof
