// Curated emoji dataset for :shortcode: autocomplete and picker
// Covers the most commonly used emojis across all categories

export interface EmojiItem {
  shortcode: string;   // e.g. "smile"
  emoji: string;       // e.g. "😄"
  keywords: string[];  // additional search terms
  category: string;    // category for picker grouping
}

export const emojiCategories = [
  { id: 'smileys', label: '😀', title: 'Smileys & People' },
  { id: 'gestures', label: '👋', title: 'Gestures & Hands' },
  { id: 'hearts', label: '❤️', title: 'Hearts & Emotions' },
  { id: 'objects', label: '🔧', title: 'Objects & Symbols' },
  { id: 'food', label: '☕', title: 'Food & Drink' },
  { id: 'nature', label: '🌿', title: 'Nature & Weather' },
  { id: 'animals', label: '🐶', title: 'Animals' },
  { id: 'tech', label: '💻', title: 'Tech & Work' },
  { id: 'misc', label: '🚩', title: 'Flags & Misc' },
];

export const emojiData: EmojiItem[] = [
  // ── Smileys & People ────────────────────────────
  { shortcode: 'smile', emoji: '😄', keywords: ['happy', 'joy', 'laugh'], category: 'smileys' },
  { shortcode: 'grinning', emoji: '😀', keywords: ['happy', 'smile'], category: 'smileys' },
  { shortcode: 'grin', emoji: '😁', keywords: ['happy', 'teeth'], category: 'smileys' },
  { shortcode: 'laughing', emoji: '😆', keywords: ['happy', 'haha'], category: 'smileys' },
  { shortcode: 'sweat_smile', emoji: '😅', keywords: ['hot', 'relief'], category: 'smileys' },
  { shortcode: 'rofl', emoji: '🤣', keywords: ['rolling', 'floor', 'laugh'], category: 'smileys' },
  { shortcode: 'joy', emoji: '😂', keywords: ['tears', 'laugh', 'cry'], category: 'smileys' },
  { shortcode: 'slightly_smiling_face', emoji: '🙂', keywords: ['okay'], category: 'smileys' },
  { shortcode: 'upside_down_face', emoji: '🙃', keywords: ['silly', 'sarcasm'], category: 'smileys' },
  { shortcode: 'wink', emoji: '😉', keywords: ['flirt'], category: 'smileys' },
  { shortcode: 'blush', emoji: '😊', keywords: ['shy', 'happy'], category: 'smileys' },
  { shortcode: 'innocent', emoji: '😇', keywords: ['angel', 'halo'], category: 'smileys' },
  { shortcode: 'heart_eyes', emoji: '😍', keywords: ['love', 'crush'], category: 'smileys' },
  { shortcode: 'star_struck', emoji: '🤩', keywords: ['wow', 'amazing'], category: 'smileys' },
  { shortcode: 'kissing_heart', emoji: '😘', keywords: ['love', 'kiss'], category: 'smileys' },
  { shortcode: 'kissing', emoji: '😗', keywords: ['kiss'], category: 'smileys' },
  { shortcode: 'yum', emoji: '😋', keywords: ['delicious', 'tongue'], category: 'smileys' },
  { shortcode: 'stuck_out_tongue', emoji: '😛', keywords: ['playful'], category: 'smileys' },
  { shortcode: 'stuck_out_tongue_winking_eye', emoji: '😜', keywords: ['playful', 'joke'], category: 'smileys' },
  { shortcode: 'zany_face', emoji: '🤪', keywords: ['crazy', 'wild'], category: 'smileys' },
  { shortcode: 'thinking', emoji: '🤔', keywords: ['hmm', 'consider'], category: 'smileys' },
  { shortcode: 'shushing_face', emoji: '🤫', keywords: ['quiet', 'secret'], category: 'smileys' },
  { shortcode: 'hand_over_mouth', emoji: '🤭', keywords: ['oops', 'giggle'], category: 'smileys' },
  { shortcode: 'zipper_mouth_face', emoji: '🤐', keywords: ['secret', 'sealed'], category: 'smileys' },
  { shortcode: 'raised_eyebrow', emoji: '🤨', keywords: ['skeptic', 'suspicious'], category: 'smileys' },
  { shortcode: 'neutral_face', emoji: '😐', keywords: ['meh'], category: 'smileys' },
  { shortcode: 'expressionless', emoji: '😑', keywords: ['blank'], category: 'smileys' },
  { shortcode: 'no_mouth', emoji: '😶', keywords: ['silent', 'speechless'], category: 'smileys' },
  { shortcode: 'smirk', emoji: '😏', keywords: ['suggestive', 'flirt'], category: 'smileys' },
  { shortcode: 'unamused', emoji: '😒', keywords: ['annoyed', 'unhappy'], category: 'smileys' },
  { shortcode: 'roll_eyes', emoji: '🙄', keywords: ['whatever', 'bored'], category: 'smileys' },
  { shortcode: 'grimacing', emoji: '😬', keywords: ['awkward', 'nervous'], category: 'smileys' },
  { shortcode: 'relieved', emoji: '😌', keywords: ['calm', 'peace'], category: 'smileys' },
  { shortcode: 'pensive', emoji: '😔', keywords: ['sad', 'thoughtful'], category: 'smileys' },
  { shortcode: 'sleepy', emoji: '😪', keywords: ['tired'], category: 'smileys' },
  { shortcode: 'sleeping', emoji: '😴', keywords: ['zzz', 'asleep'], category: 'smileys' },
  { shortcode: 'mask', emoji: '😷', keywords: ['sick', 'covid'], category: 'smileys' },
  { shortcode: 'nerd_face', emoji: '🤓', keywords: ['geek', 'glasses'], category: 'smileys' },
  { shortcode: 'sunglasses', emoji: '😎', keywords: ['cool', 'awesome'], category: 'smileys' },
  { shortcode: 'disguised_face', emoji: '🥸', keywords: ['incognito'], category: 'smileys' },
  { shortcode: 'confused', emoji: '😕', keywords: ['uncertain'], category: 'smileys' },
  { shortcode: 'worried', emoji: '😟', keywords: ['anxious', 'concern'], category: 'smileys' },
  { shortcode: 'frowning_face', emoji: '☹️', keywords: ['sad'], category: 'smileys' },
  { shortcode: 'open_mouth', emoji: '😮', keywords: ['surprised', 'shocked'], category: 'smileys' },
  { shortcode: 'astonished', emoji: '😲', keywords: ['surprised', 'shocked'], category: 'smileys' },
  { shortcode: 'flushed', emoji: '😳', keywords: ['embarrassed'], category: 'smileys' },
  { shortcode: 'pleading_face', emoji: '🥺', keywords: ['puppy', 'please'], category: 'smileys' },
  { shortcode: 'cry', emoji: '😢', keywords: ['sad', 'tear'], category: 'smileys' },
  { shortcode: 'sob', emoji: '😭', keywords: ['sad', 'crying', 'tears'], category: 'smileys' },
  { shortcode: 'scream', emoji: '😱', keywords: ['horror', 'scared'], category: 'smileys' },
  { shortcode: 'angry', emoji: '😠', keywords: ['mad', 'furious'], category: 'smileys' },
  { shortcode: 'rage', emoji: '😡', keywords: ['angry', 'mad'], category: 'smileys' },
  { shortcode: 'swearing', emoji: '🤬', keywords: ['curse', 'angry'], category: 'smileys' },
  { shortcode: 'skull', emoji: '💀', keywords: ['dead', 'death'], category: 'smileys' },
  { shortcode: 'poop', emoji: '💩', keywords: ['shit'], category: 'smileys' },
  { shortcode: 'clown_face', emoji: '🤡', keywords: ['funny'], category: 'smileys' },
  { shortcode: 'ghost', emoji: '👻', keywords: ['halloween', 'boo'], category: 'smileys' },
  { shortcode: 'alien', emoji: '👽', keywords: ['ufo', 'space'], category: 'smileys' },
  { shortcode: 'robot', emoji: '🤖', keywords: ['bot', 'ai'], category: 'smileys' },
  { shortcode: 'smiley_cat', emoji: '😺', keywords: ['happy', 'cat'], category: 'smileys' },
  { shortcode: 'heart_eyes_cat', emoji: '😻', keywords: ['love', 'cat'], category: 'smileys' },
  
  // ── Gestures & Hands ────────────────────────────
  { shortcode: 'wave', emoji: '👋', keywords: ['hello', 'hi', 'bye'], category: 'gestures' },
  { shortcode: 'raised_hand', emoji: '✋', keywords: ['stop', 'high five'], category: 'gestures' },
  { shortcode: 'ok_hand', emoji: '👌', keywords: ['perfect', 'nice'], category: 'gestures' },
  { shortcode: 'pinching_hand', emoji: '🤏', keywords: ['small', 'tiny'], category: 'gestures' },
  { shortcode: 'v', emoji: '✌️', keywords: ['peace', 'victory'], category: 'gestures' },
  { shortcode: 'crossed_fingers', emoji: '🤞', keywords: ['luck', 'hope'], category: 'gestures' },
  { shortcode: 'love_you', emoji: '🤟', keywords: ['ily'], category: 'gestures' },
  { shortcode: 'metal', emoji: '🤘', keywords: ['rock', 'horns'], category: 'gestures' },
  { shortcode: 'call_me_hand', emoji: '🤙', keywords: ['shaka'], category: 'gestures' },
  { shortcode: 'point_left', emoji: '👈', keywords: ['left'], category: 'gestures' },
  { shortcode: 'point_right', emoji: '👉', keywords: ['right'], category: 'gestures' },
  { shortcode: 'point_up', emoji: '👆', keywords: ['up'], category: 'gestures' },
  { shortcode: 'point_down', emoji: '👇', keywords: ['down'], category: 'gestures' },
  { shortcode: 'thumbsup', emoji: '👍', keywords: ['yes', 'good', 'like', '+1'], category: 'gestures' },
  { shortcode: 'thumbsdown', emoji: '👎', keywords: ['no', 'bad', 'dislike', '-1'], category: 'gestures' },
  { shortcode: 'fist', emoji: '✊', keywords: ['power', 'punch'], category: 'gestures' },
  { shortcode: 'fist_bump', emoji: '🤜', keywords: ['bro'], category: 'gestures' },
  { shortcode: 'clap', emoji: '👏', keywords: ['applause', 'bravo'], category: 'gestures' },
  { shortcode: 'raised_hands', emoji: '🙌', keywords: ['celebrate', 'praise'], category: 'gestures' },
  { shortcode: 'handshake', emoji: '🤝', keywords: ['deal', 'agreement'], category: 'gestures' },
  { shortcode: 'pray', emoji: '🙏', keywords: ['please', 'thanks', 'hope', 'namaste'], category: 'gestures' },
  { shortcode: 'writing_hand', emoji: '✍️', keywords: ['write'], category: 'gestures' },
  { shortcode: 'muscle', emoji: '💪', keywords: ['strong', 'flex', 'gym'], category: 'gestures' },
  
  // ── Hearts & Emotions ──────────────────────────
  { shortcode: 'heart', emoji: '❤️', keywords: ['love', 'red'], category: 'hearts' },
  { shortcode: 'orange_heart', emoji: '🧡', keywords: ['love'], category: 'hearts' },
  { shortcode: 'yellow_heart', emoji: '💛', keywords: ['love'], category: 'hearts' },
  { shortcode: 'green_heart', emoji: '💚', keywords: ['love'], category: 'hearts' },
  { shortcode: 'blue_heart', emoji: '💙', keywords: ['love'], category: 'hearts' },
  { shortcode: 'purple_heart', emoji: '💜', keywords: ['love'], category: 'hearts' },
  { shortcode: 'black_heart', emoji: '🖤', keywords: ['love'], category: 'hearts' },
  { shortcode: 'white_heart', emoji: '🤍', keywords: ['love'], category: 'hearts' },
  { shortcode: 'broken_heart', emoji: '💔', keywords: ['sad', 'break'], category: 'hearts' },
  { shortcode: 'fire_heart', emoji: '❤️‍🔥', keywords: ['passion'], category: 'hearts' },
  { shortcode: 'sparkling_heart', emoji: '💖', keywords: ['love'], category: 'hearts' },
  { shortcode: 'heartbeat', emoji: '💓', keywords: ['pulse'], category: 'hearts' },
  { shortcode: 'two_hearts', emoji: '💕', keywords: ['love'], category: 'hearts' },
  { shortcode: 'revolving_hearts', emoji: '💞', keywords: ['love'], category: 'hearts' },
  { shortcode: 'cupid', emoji: '💘', keywords: ['love', 'arrow'], category: 'hearts' },
  { shortcode: '100', emoji: '💯', keywords: ['perfect', 'score'], category: 'hearts' },
  { shortcode: 'boom', emoji: '💥', keywords: ['explosion', 'collision'], category: 'hearts' },
  { shortcode: 'star', emoji: '⭐', keywords: ['favorite'], category: 'hearts' },
  { shortcode: 'star2', emoji: '🌟', keywords: ['glowing', 'sparkle'], category: 'hearts' },
  { shortcode: 'sparkles', emoji: '✨', keywords: ['magic', 'shine', 'new'], category: 'hearts' },
  { shortcode: 'zap', emoji: '⚡', keywords: ['lightning', 'fast', 'electric'], category: 'hearts' },
  { shortcode: 'fire', emoji: '🔥', keywords: ['hot', 'lit', 'flame'], category: 'hearts' },
  
  // ── Objects & Symbols ──────────────────────────
  { shortcode: 'check', emoji: '✅', keywords: ['done', 'yes', 'complete'], category: 'objects' },
  { shortcode: 'x', emoji: '❌', keywords: ['no', 'wrong', 'cancel'], category: 'objects' },
  { shortcode: 'warning', emoji: '⚠️', keywords: ['alert', 'caution'], category: 'objects' },
  { shortcode: 'question', emoji: '❓', keywords: ['what', 'help'], category: 'objects' },
  { shortcode: 'exclamation', emoji: '❗', keywords: ['important', 'alert'], category: 'objects' },
  { shortcode: 'bulb', emoji: '💡', keywords: ['idea', 'light', 'tip'], category: 'objects' },
  { shortcode: 'memo', emoji: '📝', keywords: ['note', 'write'], category: 'objects' },
  { shortcode: 'pushpin', emoji: '📌', keywords: ['pin', 'location'], category: 'objects' },
  { shortcode: 'link', emoji: '🔗', keywords: ['url', 'chain'], category: 'objects' },
  { shortcode: 'lock', emoji: '🔒', keywords: ['security', 'private'], category: 'objects' },
  { shortcode: 'unlock', emoji: '🔓', keywords: ['open', 'free'], category: 'objects' },
  { shortcode: 'key', emoji: '🔑', keywords: ['password', 'access'], category: 'objects' },
  { shortcode: 'gear', emoji: '⚙️', keywords: ['settings', 'config'], category: 'objects' },
  { shortcode: 'hammer', emoji: '🔨', keywords: ['build', 'tool'], category: 'objects' },
  { shortcode: 'wrench', emoji: '🔧', keywords: ['fix', 'tool'], category: 'objects' },
  { shortcode: 'mag', emoji: '🔍', keywords: ['search', 'zoom'], category: 'objects' },
  { shortcode: 'bell', emoji: '🔔', keywords: ['notification', 'alert'], category: 'objects' },
  { shortcode: 'calendar', emoji: '📅', keywords: ['date', 'schedule'], category: 'objects' },
  { shortcode: 'clock', emoji: '🕐', keywords: ['time', 'hour'], category: 'objects' },
  { shortcode: 'hourglass', emoji: '⏳', keywords: ['time', 'wait'], category: 'objects' },
  { shortcode: 'stopwatch', emoji: '⏱️', keywords: ['timer', 'speed'], category: 'objects' },
  { shortcode: 'trophy', emoji: '🏆', keywords: ['winner', 'award'], category: 'objects' },
  { shortcode: 'medal', emoji: '🏅', keywords: ['award', 'achievement'], category: 'objects' },
  { shortcode: 'crown', emoji: '👑', keywords: ['king', 'queen', 'royalty'], category: 'objects' },
  { shortcode: 'gem', emoji: '💎', keywords: ['diamond', 'precious'], category: 'objects' },
  { shortcode: 'money_bag', emoji: '💰', keywords: ['rich', 'dollar'], category: 'objects' },
  { shortcode: 'dollar', emoji: '💵', keywords: ['money', 'cash'], category: 'objects' },
  { shortcode: 'chart', emoji: '📈', keywords: ['growth', 'increase', 'stonks'], category: 'objects' },
  { shortcode: 'chart_down', emoji: '📉', keywords: ['decline', 'decrease'], category: 'objects' },
  { shortcode: 'rocket', emoji: '🚀', keywords: ['launch', 'fast', 'ship'], category: 'objects' },
  { shortcode: 'airplane', emoji: '✈️', keywords: ['travel', 'flight'], category: 'objects' },
  { shortcode: 'tada', emoji: '🎉', keywords: ['party', 'celebrate', 'congratulations'], category: 'objects' },
  { shortcode: 'confetti_ball', emoji: '🎊', keywords: ['celebrate'], category: 'objects' },
  { shortcode: 'balloon', emoji: '🎈', keywords: ['party', 'birthday'], category: 'objects' },
  { shortcode: 'gift', emoji: '🎁', keywords: ['present', 'birthday'], category: 'objects' },
  { shortcode: 'ribbon', emoji: '🎀', keywords: ['bow', 'decoration'], category: 'objects' },
  
  // ── Food & Drink ──────────────────────────────
  { shortcode: 'coffee', emoji: '☕', keywords: ['cafe', 'morning', 'drink'], category: 'food' },
  { shortcode: 'tea', emoji: '🍵', keywords: ['green', 'drink'], category: 'food' },
  { shortcode: 'beer', emoji: '🍺', keywords: ['drink', 'cheers'], category: 'food' },
  { shortcode: 'wine_glass', emoji: '🍷', keywords: ['drink', 'red'], category: 'food' },
  { shortcode: 'pizza', emoji: '🍕', keywords: ['food', 'italian'], category: 'food' },
  { shortcode: 'hamburger', emoji: '🍔', keywords: ['food', 'burger'], category: 'food' },
  { shortcode: 'cake', emoji: '🎂', keywords: ['birthday', 'dessert'], category: 'food' },
  { shortcode: 'cookie', emoji: '🍪', keywords: ['biscuit', 'snack'], category: 'food' },
  { shortcode: 'ice_cream', emoji: '🍦', keywords: ['dessert', 'sweet'], category: 'food' },
  
  // ── Nature & Weather ──────────────────────────
  { shortcode: 'sun', emoji: '☀️', keywords: ['bright', 'weather'], category: 'nature' },
  { shortcode: 'moon', emoji: '🌙', keywords: ['night', 'crescent'], category: 'nature' },
  { shortcode: 'cloud', emoji: '☁️', keywords: ['weather', 'sky'], category: 'nature' },
  { shortcode: 'rain', emoji: '🌧️', keywords: ['weather', 'wet'], category: 'nature' },
  { shortcode: 'snow', emoji: '❄️', keywords: ['cold', 'winter'], category: 'nature' },
  { shortcode: 'rainbow', emoji: '🌈', keywords: ['colors', 'pride'], category: 'nature' },
  { shortcode: 'ocean', emoji: '🌊', keywords: ['wave', 'sea'], category: 'nature' },
  { shortcode: 'earth', emoji: '🌍', keywords: ['globe', 'world'], category: 'nature' },
  { shortcode: 'tree', emoji: '🌳', keywords: ['nature', 'green'], category: 'nature' },
  { shortcode: 'flower', emoji: '🌸', keywords: ['cherry', 'blossom', 'spring'], category: 'nature' },
  { shortcode: 'rose', emoji: '🌹', keywords: ['flower', 'love'], category: 'nature' },
  { shortcode: 'seedling', emoji: '🌱', keywords: ['plant', 'grow', 'new'], category: 'nature' },
  { shortcode: 'four_leaf_clover', emoji: '🍀', keywords: ['luck', 'irish'], category: 'nature' },
  
  // ── Animals ───────────────────────────────────
  { shortcode: 'dog', emoji: '🐶', keywords: ['puppy', 'pet'], category: 'animals' },
  { shortcode: 'cat', emoji: '🐱', keywords: ['kitten', 'pet', 'meow'], category: 'animals' },
  { shortcode: 'fox', emoji: '🦊', keywords: ['animal'], category: 'animals' },
  { shortcode: 'bear', emoji: '🐻', keywords: ['animal'], category: 'animals' },
  { shortcode: 'panda', emoji: '🐼', keywords: ['animal', 'cute'], category: 'animals' },
  { shortcode: 'penguin', emoji: '🐧', keywords: ['animal', 'cold'], category: 'animals' },
  { shortcode: 'bird', emoji: '🐦', keywords: ['animal', 'tweet'], category: 'animals' },
  { shortcode: 'butterfly', emoji: '🦋', keywords: ['insect', 'beautiful'], category: 'animals' },
  { shortcode: 'unicorn', emoji: '🦄', keywords: ['magic', 'fantasy'], category: 'animals' },
  { shortcode: 'bee', emoji: '🐝', keywords: ['honey', 'insect'], category: 'animals' },
  { shortcode: 'bug', emoji: '🐛', keywords: ['insect', 'debug'], category: 'animals' },
  
  // ── Tech & Work ───────────────────────────────
  { shortcode: 'computer', emoji: '💻', keywords: ['laptop', 'code', 'work'], category: 'tech' },
  { shortcode: 'phone', emoji: '📱', keywords: ['mobile', 'cell'], category: 'tech' },
  { shortcode: 'keyboard', emoji: '⌨️', keywords: ['type', 'code'], category: 'tech' },
  { shortcode: 'desktop', emoji: '🖥️', keywords: ['monitor', 'screen'], category: 'tech' },
  { shortcode: 'printer', emoji: '🖨️', keywords: ['print'], category: 'tech' },
  { shortcode: 'mouse', emoji: '🖱️', keywords: ['click', 'cursor'], category: 'tech' },
  { shortcode: 'floppy_disk', emoji: '💾', keywords: ['save'], category: 'tech' },
  { shortcode: 'cd', emoji: '💿', keywords: ['disc', 'music'], category: 'tech' },
  { shortcode: 'package', emoji: '📦', keywords: ['box', 'delivery'], category: 'tech' },
  { shortcode: 'email', emoji: '📧', keywords: ['mail', 'message'], category: 'tech' },
  { shortcode: 'inbox', emoji: '📥', keywords: ['receive'], category: 'tech' },
  { shortcode: 'outbox', emoji: '📤', keywords: ['send'], category: 'tech' },
  { shortcode: 'file_folder', emoji: '📁', keywords: ['directory'], category: 'tech' },
  { shortcode: 'clipboard', emoji: '📋', keywords: ['paste', 'list'], category: 'tech' },
  { shortcode: 'bar_chart', emoji: '📊', keywords: ['stats', 'graph'], category: 'tech' },
  { shortcode: 'books', emoji: '📚', keywords: ['read', 'study', 'library'], category: 'tech' },
  { shortcode: 'newspaper', emoji: '📰', keywords: ['news', 'press'], category: 'tech' },
  
  // ── Flags & Misc ──────────────────────────────
  { shortcode: 'flag_white', emoji: '🏳️', keywords: ['surrender'], category: 'misc' },
  { shortcode: 'checkered_flag', emoji: '🏁', keywords: ['finish', 'race'], category: 'misc' },
  { shortcode: 'triangular_flag', emoji: '🚩', keywords: ['red flag', 'warning'], category: 'misc' },
  { shortcode: 'eyes', emoji: '👀', keywords: ['look', 'see', 'watch'], category: 'misc' },
  { shortcode: 'brain', emoji: '🧠', keywords: ['think', 'smart', 'mind'], category: 'misc' },
  { shortcode: 'speech_balloon', emoji: '💬', keywords: ['talk', 'chat', 'comment'], category: 'misc' },
  { shortcode: 'thought_balloon', emoji: '💭', keywords: ['think', 'dream'], category: 'misc' },
  { shortcode: 'zzz', emoji: '💤', keywords: ['sleep', 'tired'], category: 'misc' },
  { shortcode: 'wave_dash', emoji: '〰️', keywords: ['line'], category: 'misc' },
  { shortcode: 'infinity', emoji: '♾️', keywords: ['forever', 'unlimited'], category: 'misc' },
  { shortcode: 'recycle', emoji: '♻️', keywords: ['environment', 'green'], category: 'misc' },
  { shortcode: 'atom', emoji: '⚛️', keywords: ['science', 'react'], category: 'misc' },
  { shortcode: 'yin_yang', emoji: '☯️', keywords: ['balance'], category: 'misc' },
  { shortcode: 'peace', emoji: '☮️', keywords: ['hippie'], category: 'misc' },
  { shortcode: 'arrow_right', emoji: '➡️', keywords: ['next', 'forward'], category: 'misc' },
  { shortcode: 'arrow_left', emoji: '⬅️', keywords: ['back', 'previous'], category: 'misc' },
  { shortcode: 'arrow_up', emoji: '⬆️', keywords: ['top'], category: 'misc' },
  { shortcode: 'arrow_down', emoji: '⬇️', keywords: ['bottom'], category: 'misc' },
];
