use ed25519_dalek::{VerifyingKey, Signature, Verifier};
use hex;

// We will embed the public key generated by our license-server at compile time.
// Since it's a public key, embedding it directly in the client is completely safe.
const LICENSE_PUBLIC_KEY_HEX: &str = match option_env!("LICENSE_PUBLIC_KEY") {
    Some(k) => k,
    None => "0000000000000000000000000000000000000000000000000000000000000000"
};

pub fn verify_license_signature(data: &str, signature_hex: &str) -> bool {
    // Parse public key
    let pub_key_bytes = match hex::decode(LICENSE_PUBLIC_KEY_HEX) {
        Ok(b) => b,
        Err(_) => return false,
    };
    
    let mut pub_key_array = [0u8; 32];
    if pub_key_bytes.len() != 32 {
        return false;
    }
    pub_key_array.copy_from_slice(&pub_key_bytes);
    
    let verifying_key = match VerifyingKey::from_bytes(&pub_key_array) {
        Ok(k) => k,
        Err(_) => return false,
    };

    // Parse signature
    let sig_bytes = match hex::decode(signature_hex) {
        Ok(b) => b,
        Err(_) => return false,
    };
    
    let signature = match Signature::from_slice(&sig_bytes) {
        Ok(s) => s,
        Err(_) => return false,
    };

    // Verify
    verifying_key.verify(data.as_bytes(), &signature).is_ok()
}
